In [1]:
# https://nbviewer.jupyter.org/github/fastai/numerical-linear-algebra-v2/blob/master/nbs/01-Why-are-we-here.ipynb 

In [2]:
# Exercise 1: HIV and AIDS Problem

In [3]:
import numpy as np
import sklearn

In [41]:
states = np.array([[0.85, 0.10, 0.05, 0.00]])

In [5]:
stochastic_matrix = np.array([
    [0.90, 0.07, 0.02, 0.01],
    [0.00, 0.93, 0.05, 0.02],
    [0.00, 0.00, 0.85, 0.15],
    [0.00, 0.00, 0.00, 1.00]
])

In [40]:
stochastic_matrix.T @ states.T

array([[ 0.9 ],
       [ 0.07],
       [ 0.02],
       [ 0.01]])

In [8]:
stochastic_matrix

array([[ 0.9 ,  0.07,  0.02,  0.01],
       [ 0.  ,  0.93,  0.05,  0.02],
       [ 0.  ,  0.  ,  0.85,  0.15],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [9]:
# Exercise 2: 

In [10]:
people_needs = np.array([
    [6, 5, 3, 1],
    [3, 6, 2, 2],
    [3, 4, 3, 1]
])

In [11]:
prices = np.array([
    [1.50, 1.00],
    [2.00, 2.50],
    [5.00, 4.50],
    [16.0, 17.0]
])

In [12]:
people_needs @ prices

array([[ 50. ,  49. ],
       [ 58.5,  61. ],
       [ 43.5,  43.5]])